### PR TITLE
Run tests with Travis CI

### PR DESCRIPTION
**Pull request by rouge8**
Use [Travis CI](https://travis-ci.org) to build pull requests and branches.

### CODE REVIEW

**Comment by rouge8** [comment]
@dcreager ready for review pending build success

**Comment by rouge8** [comment]
@dcreager the failures here are actual test failure, not build errors.

**Comment by dcreager** [comment]
I don't get those test failures locally, so I want to hammer out the regression before I merge this.  (I.e., I want to make sure it's not an issue with how we're having Travis run everything.)

**Comment by rouge8** [comment]
Rebased onto the latest develop and still get the failures. I don't get them locally on an Ubuntu box though...

**Comment by dcreager** [comment]
I think I found the regression: #12.  It wasn't getting caught locally because of redjack/libcork#104 — you probably had a version of libcork installed where the debug allocator's check was compiled out.

**Comment by dcreager** [comment]
The tests pass with #12 applied, so I'm going to merge this; I want to do it in this order so that I get the nice green check mark for that PR!

**Pull request merged**
